# Generated by Django 6.0 on 2025-12-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trilha', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=150)),
                ('conteudo', models.TextField()),
                ('imagem', models.CharField(help_text='Ex: mestre/img/aula1.png', max_length=200)),
            ],
        ),
    ]
