# Generated by Django 6.0 on 2025-12-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mestre', '0002_progresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresso',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
